### ISSUE TITLE
Shopper Search productSearch does not include new query parameters

### ISSUE THREAD

**Issue by joeluong-sfcc** [SalesforceCommerceCloud/commerce-sdk-isomorphic#143]
According to the [developer docs](https://developer.salesforce.com/docs/commerce/commerce-api/references/shopper-search?meta=productSearch), `productSearch` endpoint should accept new query parameters `allImages` and `select`. However, this is not supported in the `commerce-sdk-isomorphic`: https://salesforcecommercecloud.github.io/commerce-sdk-isomorphic/classes/shoppersearch.shoppersearch-1.html#productsearch

**Comment by johnboxall** [comment]
@joeluong-sfcc – FYI, these params are introduced in B2C Commerce 24.3 – we jumped the gun a little bit on publishing them to DSC!

**Comment by nilay-macwan** [comment]
Hi @johnboxall @vmarta @natemarcus,

Could you kindly provide an update on when we can expect this to be added to `commerce-sdk` ? Specifically, the select parameter for the product-search endpoint (https://salesforcecommercecloud.github.io/commerce-sdk/classes/search.shoppersearch.html#productsearch).

It’s been over a year since this functionality was introduced for the endpoint, but the `commerce-sdk` still seems to lack support for it. Could you shed some light on what’s causing the delay or share any updates on the roadmap ?

Looking forward to your insights!

**Comment by joeluong-sfcc** [comment]
Hi @nilay-macwan, thanks for bringing up this issue.

This is actually a bug and the `commerce-sdk` should be including that query parameter. We're currently preparing for a major version release of both the `commerce-sdk` and `commerce-sdk-isomorphic`. In that release, this issue will be resolved.

Although not ideal, a workaround would to be use the fetch API and call SCAPI directly to pass in those query parameters.

**Comment by nilay-macwan** [comment]
@joeluong-sfcc Thank you for the feedback! Do you have an ETA on the major version release ?

**Comment by joeluong-sfcc** [comment]
Tentatively sometime in June

**Comment by davidwieler** [comment]
@joeluong-sfcc Are the docs for the major version bump available somewhere now, even if in beta?
We would love to get ahead of this if possible.

**Comment by Venkatasainath93** [comment]
@joeluong-sfcc is there any update on the version release?
